---
variables:
  PACKAGE_NAME: val_description
  CONFIGURATIONS_FILE: .configurations.yml
  RUN_TESTS: "false"
  DEBIAN_PACKAGE_NAME: "val-description"

stages:
  - build
  - package
  - deploy

include:
  - project: ci_build/workspace_tools
    file: gitlab_templates/ros/ros.yml
    ref: develop

before_script:
  - echo "yaml https://js-er-code.jsc.nasa.gov/nc/nasa_common_rosdep/raw/develop/nasa-common.yaml" > /etc/ros/rosdep/sources.list.d/10-nasa-common.list 
  - echo "yaml https://js-er-code.jsc.nasa.gov/nc/nasa_common_rosdep/raw/develop/nasa-common-deb.yaml" > /etc/ros/rosdep/sources.list.d/11-nasa-common-deb.list 
  - echo "yaml https://js-er-code.jsc.nasa.gov/vs/val_rosdep/raw/develop/nasa-val-deb.yaml" > /etc/ros/rosdep/sources.list.d/12-nasa-val-deb.list 
  - apt-get update -qqy
  - rosdep update

focal_noetic_build:
  stage: build
  variables:
    ROS_DISTRO: noetic
    CONFIGURATION: noetic
  image: js-er-code.jsc.nasa.gov:5005/ci_build/ubuntu_focal_dockers/ros_noetic_with_nc
  extends: .RosBuildGenerateWorkspaceFromConfiguration

focal_noetic_package:
  stage: package
  variables:
    CONFIGURATION: noetic
  image: js-er-code.jsc.nasa.gov:5005/ci_build/ubuntu_focal_dockers/ros_noetic_with_nc
  extends: .RosGenerateDebian
  except:
    - schedules
  dependencies:
    - focal_noetic_build

focal_noetic_deploy:
  stage: deploy
  variables:
    CONFIGURATION: noetic
    DEB_REPO: "ubuntu-focal"
  image: js-er-code.jsc.nasa.gov:5005/ci_build/ubuntu_focal_dockers/ros_noetic_with_nc
  extends: .RosDeployDebianArtifactory
  except:
    - schedules
  dependencies:
    - focal_noetic_package
