<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="v1/arm">

  <xacro:include filename="$(find valkyrie_description)/robots/valkyrie_A/xacro/arm/joint_names.xacro"/>
  <xacro:include filename="$(find valkyrie_description)/robots/valkyrie_A/xacro/arm/link_names.xacro"/>
  <xacro:include filename="$(find valkyrie_description)/robots/valkyrie_A/xacro/arm/joint_limits.xacro"/>
  <xacro:include filename="$(find valkyrie_description)/robots/valkyrie_A/xacro/arm/frame_parameters.xacro"/>
  <xacro:include filename="$(find valkyrie_description)/robots/valkyrie_A/xacro/arm/mass_parameters.xacro"/>
  <xacro:include filename="$(find valkyrie_description)/robots/valkyrie_A/xacro/sensors/camboard.xacro"/>

  <xacro:property name="AJ1_Link_Width" value="0.162"/>
  <xacro:property name="AJ1_Link_Height" value="0.202"/>
  <xacro:property name="AJ1_Link_Length" value="0.146"/>

  <xacro:property name="AJ2_Link_Width" value="0.22179303376297454520"/>
  <xacro:property name="AJ2_Link_Height" value="0.16373203016010165478"/>
  <xacro:property name="AJ2_Link_Length" value="0.15560348965569942292"/>

  <xacro:property name="AJ3_Link_Width" value="0.136"/>
  <xacro:property name="AJ3_Link_Height" value="0.158"/>
  <xacro:property name="AJ3_Link_Length" value="0.285"/>

  <xacro:property name="AJ4_Link_Width" value="0.11323257841518076516"/>
  <xacro:property name="AJ4_Link_Height" value="0.11855222975004402197"/>
  <xacro:property name="AJ4_Link_Length" value="0.10487312631734664603"/>

  <xacro:property name="AJ5_Link_Width" value="0.13557189311158912570"/>
  <xacro:property name="AJ5_Link_Height" value="0.11439484172804967321"/>
  <xacro:property name="AJ5_Link_Length" value="0.25365181285234167374"/>

  <xacro:property name="AJ6_Link_Width" value="0.03"/>
  <xacro:property name="AJ6_Link_Height" value="0.01"/>
  <xacro:property name="AJ6_Link_Length" value="0.051"/>

  <xacro:property name="AJ7_Link_Width" value="0.085"/>
  <xacro:property name="AJ7_Link_Height" value="0.1"/>
  <xacro:property name="AJ7_Link_Length" value="0.038"/>


  <xacro:macro name="make_upper_arm" params="prefix reflect upper_arm_root_link">
    <!-- LINKS -->
    <xacro:box_link name="${AJ1_Distal_Link}"
                    width="${AJ1_Link_Width}" height="${AJ1_Link_Height}" depth="${AJ1_Link_Length}" mass="${AJ1_Link_Mass}"
                    origin_xyz="0 -0.01204 ${reflect * -0.251}" origin_rpy="0 0 0"
                    visual_mesh="${mesh_root}/aj1_${prefix}.stl"
                    material="Gold"
                    collision_mesh="${mesh_root}/aj1_${prefix}.stl" />

    <xacro:box_link name="${AJ2_Distal_Link}"
                    width="${AJ2_Link_Width}" height="${AJ2_Link_Height}" depth="${AJ2_Link_Length}" mass="${AJ2_Link_Mass}"
                    origin_xyz="0.04 0.005 ${reflect * -0.02}" origin_rpy="0 0 0"
                    visual_mesh="${mesh_root}/aj2.stl"
                    material="White"
                    collision_mesh="${mesh_root}/aj2.stl" />

    <xacro:box_link name="${AJ3_Distal_Link}"
                    width="${AJ3_Link_Width}" height="${AJ3_Link_Height}" depth="${AJ3_Link_Length}" mass="${AJ3_Link_Mass}"
                    origin_xyz="${reflect * 0.02} ${reflect * -0.004} ${reflect * -0.273}" origin_rpy="0 0 0"
                    visual_mesh="${mesh_root}/aj3_${prefix}.stl"
                    material="White"
                    collision_mesh="${mesh_root}/aj3_${prefix}.stl" />

    <xacro:box_link name="${AJ4_Distal_Link}"
                    width="${AJ4_Link_Width}" height="${AJ4_Link_Height}" depth="${AJ4_Link_Length}" mass="${AJ4_Link_Mass}"
                    origin_rpy="0 0 0"
                    origin_xyz="0.0270 -0.0802 0"
                    visual_mesh="${mesh_root}/aj4.stl"
                    material="Gold"
                    collision_mesh="${mesh_root}/aj4.stl" />

    <!-- AJ1 -->
    <xacro:revolute_joint_ex jointName="${AJ1_Joint_Name}"
                          parent="${upper_arm_root_link}" child="${AJ1_Distal_Link}"
                          origin_xyz="${ShoulderPitchFrameOrigin_X} ${ShoulderPitchFrameOrigin_Y} ${ShoulderPitchFrameOrigin_Z}"
                          origin_rpy="${ShoulderPitchFrameOrientation_Roll} ${ShoulderPitchFrameOrientation_Pitch} ${ShoulderPitchFrameOrientation_Yaw}"
                          damping="1.0" friction="0.0">
        <limit effort="${ShoulderPitchTorqueLimit}" lower="${ShoulderPitchPositionLimit_Lower}" upper="${ShoulderPitchPositionLimit_Upper}" velocity="${AJ1_Speed_Limit}"/>
        <controller_gains Kp="20000" Kd="400"/>
    </xacro:revolute_joint_ex>

    <!-- AJ2 -->
    <xacro:revolute_joint_ex jointName="${AJ2_Joint_Name}"
                          parent="${AJ2_Proximal_Link}" child="${AJ2_Distal_Link}"
                          origin_xyz="${ShoulderRollFrameOrigin_X} ${ShoulderRollFrameOrigin_Y} ${ShoulderRollFrameOrigin_Z}"
                          origin_rpy="${ShoulderRollFrameOrientation_Roll} ${ShoulderRollFrameOrientation_Pitch} ${ShoulderRollFrameOrientation_Yaw}"
                          damping="1.0" friction="0.0">
        <limit effort="${ShoulderRollTorqueLimit}" lower="${ShoulderRollPositionLimit_Lower}" upper="${ShoulderRollPositionLimit_Upper}" velocity="${AJ2_Speed_Limit}"/>
        <controller_gains Kp="20000" Kd="400"/>
    </xacro:revolute_joint_ex>

    <!-- AJ3 -->
    <xacro:revolute_joint_ex jointName="${AJ3_Joint_Name}"
                          parent="${AJ3_Proximal_Link}" child="${AJ3_Distal_Link}"
                          origin_xyz="${ShoulderYawFrameOrigin_X} ${ShoulderYawFrameOrigin_Y} ${ShoulderYawFrameOrigin_Z}"
                          origin_rpy="${ShoulderYawFrameOrientation_Roll} ${ShoulderYawFrameOrientation_Pitch} ${ShoulderYawFrameOrientation_Yaw}"
                          damping="1.0" friction="0.0">
        <limit effort="${ShoulderYawTorqueLimit}" lower="${ShoulderYawPositionLimit_Lower}" upper="${ShoulderYawPositionLimit_Upper}" velocity="${AJ3_Speed_Limit}"/>
        <controller_gains Kp="20000" Kd="400"/>
    </xacro:revolute_joint_ex>

    <!-- AJ4 -->
    <xacro:revolute_joint_ex jointName="${AJ4_Joint_Name}"
                          parent="${AJ4_Proximal_Link}" child="${AJ4_Distal_Link}"
                          origin_xyz="${ElbowPitchFrameOrigin_X} ${ElbowPitchFrameOrigin_Y} ${ElbowPitchFrameOrigin_Z}"
                          origin_rpy="${ElbowPitchFrameOrientation_Roll} ${ElbowPitchFrameOrientation_Pitch} ${ElbowPitchFrameOrientation_Yaw}"
                          damping="1.0" friction="0.0">
        <limit effort="${ElbowPitchTorqueLimit}" lower="${ElbowPitchPositionLimit_Lower}" upper="${ElbowPitchPositionLimit_Upper}" velocity="${AJ4_Speed_Limit}"/>
        <controller_gains Kp="20000" Kd="400"/>
    </xacro:revolute_joint_ex>
  </xacro:macro>


  <xacro:macro name="make_lower_arm" params="prefix reflect lower_arm_root_link">
    <!-- LINKS -->
    <xacro:box_link name="${AJ5_Distal_Link}"
                    width="${AJ5_Link_Width}" height="${AJ5_Link_Height}" depth="${AJ5_Link_Length}" mass="${AJ5_Link_Mass}"
                    origin_rpy="0 0 0"
                    origin_xyz="0.015 ${reflect * 0.02} ${reflect * -0.11}"
                    visual_mesh="${mesh_root}/aj5_${prefix}.stl"
                    material="White"
                    collision_mesh="${mesh_root}/aj5_${prefix}.stl" />

    <xacro:box_link_no_mesh name="${AJ6_Distal_Link}"
                    width="${AJ6_Link_Width}" height="${AJ6_Link_Height}" depth="${AJ6_Link_Length}" mass="${AJ6_Link_Mass}"
                    origin_rpy="0 0 0"
                    origin_xyz="0 0 0"/>

    <xacro:box_link name="${AJ7_Distal_Link}"
                    width="${AJ7_Link_Width}" height="${AJ7_Link_Height}" depth="${AJ7_Link_Length}" mass="${AJ7_Link_Mass}"
                    origin_rpy="0 0 0"
                    origin_xyz="${AJ7_Link_Width/2} 0 0"
                    visual_mesh="${mesh_root}/palm_${prefix}.stl"
                    material="Gold"
                    collision_mesh="${mesh_root}/palm_${prefix}.stl"/>

    <!-- AJ5 -->
    <xacro:revolute_joint_ex jointName="${AJ5_Joint_Name}"
                          parent="${lower_arm_root_link}" child="${AJ5_Distal_Link}"
                          origin_xyz="${ForearmYawFrameOrigin_X} ${ForearmYawFrameOrigin_Y} ${ForearmYawFrameOrigin_Z}"
                          origin_rpy="${ForearmYawFrameOrientation_Roll} ${ForearmYawFrameOrientation_Pitch} ${ForearmYawFrameOrientation_Yaw}"
                          damping="1.0" friction="0.0">
        <limit effort="${ForearmYawTorqueLimit}" lower="${ForearmYawPositionLimit_Lower}" upper="${ForearmYawPositionLimit_Upper}" velocity="${AJ5_Speed_Limit}"/>
        <controller_gains Kp="20000" Kd="0"/>
    </xacro:revolute_joint_ex>

    <!-- AJ6 -->
    <xacro:revolute_joint_ex jointName="${AJ6_Joint_Name}"
                          parent="${AJ6_Proximal_Link}" child="${AJ6_Distal_Link}"
                          origin_xyz="${WristRollFrameOrigin_X} ${WristRollFrameOrigin_Y} ${WristRollFrameOrigin_Z}"
                          origin_rpy="${WristRollFrameOrientation_Roll} ${WristRollFrameOrientation_Pitch} ${WristRollFrameOrientation_Yaw}"
                          damping="1.0" friction="0.0">
        <limit effort="${WristRollTorqueLimit}" lower="${WristRollPositionLimit_Lower}" upper="${WristRollPositionLimit_Upper}" velocity="${AJ6_Speed_Limit}"/>
        <controller_gains Kp="20000" Kd="400"/>
    </xacro:revolute_joint_ex>

    <!-- AJ7 -->
    <xacro:revolute_joint_ex jointName="${AJ7_Joint_Name}"
                          parent="${AJ7_Proximal_Link}" child="${AJ7_Distal_Link}"
                          origin_xyz="${WristPitchFrameOrigin_X} ${WristPitchFrameOrigin_Y} ${WristPitchFrameOrigin_Z}"
                          origin_rpy="${WristPitchFrameOrientation_Roll} ${WristPitchFrameOrientation_Pitch} ${WristPitchFrameOrientation_Yaw}"
                          damping="1.0" friction="0.0">
        <limit effort="${WristPitchTorqueLimit}" lower="${WristPitchPositionLimit_Lower}" upper="${WristPitchPositionLimit_Upper}" velocity="${AJ7_Speed_Limit}"/>
        <controller_gains Kp="20000" Kd="400"/>
    </xacro:revolute_joint_ex>
  </xacro:macro>

  <xacro:macro name="make_lower_arm_fixed" params="prefix reflect lower_arm_root_link">
    <!-- LINKS -->
    <xacro:box_link name="${AJ5_Distal_Link}"
                    width="${AJ5_Link_Width}" height="${AJ5_Link_Height}" depth="${AJ5_Link_Length}" mass="${AJ5_Link_Mass}"
                    origin_rpy="0 0 0"
                    origin_xyz="0 ${reflect * 0.0006} ${reflect * -0.14}"
                    visual_mesh="${mesh_root}/aj5_${prefix}.stl"
                    material="White"
                    collision_mesh="${mesh_root}/aj5_${prefix}.stl" />

<!--     <xacro:box_link name="${AJ5_Distal_Link}"
                    width="${AJ5_Link_Width}" height="${AJ5_Link_Height}" depth="${AJ5_Link_Length}" mass="${AJ5_Link_Mass}"
                    origin_rpy="0 0 0"
                    origin_xyz="0 ${reflect * 0.0006} ${reflect * -0.176}"
                    visual_mesh="${mesh_root}/aj5_${prefix}.stl"
                    material="White"
                    collision_mesh="${mesh_root}/aj5_${prefix}.stl" />

 -->    <xacro:box_link_no_mesh name="${AJ6_Distal_Link}"
                    width="${AJ6_Link_Width}" height="${AJ6_Link_Height}" depth="${AJ6_Link_Length}" mass="${AJ6_Link_Mass}"
                    origin_rpy="0 0 0"
                    origin_xyz="0 0 0"/>

    <xacro:box_link name="${AJ7_Distal_Link}"
                    width="${AJ7_Link_Width}" height="${AJ7_Link_Height}" depth="${AJ7_Link_Length}" mass="${AJ7_Link_Mass}"
                    origin_rpy="0 0 0"
                    origin_xyz="${AJ7_Link_Width/2} 0 0"
                    visual_mesh="${mesh_root}/palm_${prefix}.stl"
                    material="Gold"
                    collision_mesh="${mesh_root}/palm_${prefix}.stl"/>

    <!-- AJ5 -->
    <xacro:fixed_joint jointName="${AJ5_Joint_Name}"
                          parent="${lower_arm_root_link}" child="${AJ5_Distal_Link}"
                          origin_xyz="${ForearmYawFrameOrigin_X} ${ForearmYawFrameOrigin_Y} ${ForearmYawFrameOrigin_Z}"
                          origin_rpy="${ForearmYawFrameOrientation_Roll} ${ForearmYawFrameOrientation_Pitch} ${ForearmYawFrameOrientation_Yaw}">
        <limit effort="${ForearmYawTorqueLimit}" lower="${ForearmYawPositionLimit_Lower}" upper="${ForearmYawPositionLimit_Upper}" velocity="${AJ5_Speed_Limit}"/>
    </xacro:fixed_joint>

    <!-- AJ6 -->
    <xacro:fixed_joint jointName="${AJ6_Joint_Name}"
                          parent="${AJ6_Proximal_Link}" child="${AJ6_Distal_Link}"
                          origin_xyz="${WristRollFrameOrigin_X} ${WristRollFrameOrigin_Y} ${WristRollFrameOrigin_Z}"
                          origin_rpy="${WristRollFrameOrientation_Roll} ${WristRollFrameOrientation_Pitch} ${WristRollFrameOrientation_Yaw}">
        <limit effort="${WristRollTorqueLimit}" lower="${WristRollPositionLimit_Lower}" upper="${WristRollPositionLimit_Upper}" velocity="${AJ6_Speed_Limit}"/>
    </xacro:fixed_joint>

    <!-- AJ7 -->
    <xacro:fixed_joint jointName="${AJ7_Joint_Name}"
                          parent="${AJ7_Proximal_Link}" child="${AJ7_Distal_Link}"
                          origin_xyz="${WristPitchFrameOrigin_X} ${WristPitchFrameOrigin_Y} ${WristPitchFrameOrigin_Z}"
                          origin_rpy="${WristPitchFrameOrientation_Roll} ${WristPitchFrameOrientation_Pitch} ${WristPitchFrameOrientation_Yaw}">
        <limit effort="${WristPitchTorqueLimit}" lower="${WristPitchPositionLimit_Lower}" upper="${WristPitchPositionLimit_Upper}" velocity="${AJ7_Speed_Limit}"/>
    </xacro:fixed_joint>
  </xacro:macro>

  <xacro:macro name="make_arm" params="prefix reflect arm_root_link">
    <xacro:make_upper_arm prefix="${prefix}" reflect="${reflect}" upper_arm_root_link="${arm_root_link}" />
    <xacro:make_lower_arm prefix="${prefix}" reflect="${reflect}" lower_arm_root_link="${AJ5_Proximal_Link}" />
  </xacro:macro>

  <!-- Sensors -->
  <xacro:macro name="v1_right_arm_sensor">
    <xacro:camboard_sensor sensorName="/v1/RightCamBoard"
                           parentLink="/v1/RightForearm"
                           origin_xyz="0.049237 0.006877 -0.250708"
                           origin_rpy="${pi} ${pi_2} ${pi}"/>
  </xacro:macro>

  <xacro:macro name="v1_left_arm_sensor">
    <xacro:camboard_sensor sensorName="/v1/LeftCamBoard"
                           parentLink="/v1/LeftForearm"
                           origin_xyz="0.045536 -0.0085 0.250708"
                           origin_rpy="${pi} -${pi_2} 0"/>
  </xacro:macro>

  <xacro:macro name="v1_arm_sensors">
    <xacro:v1_right_arm_sensor />
    <xacro:v1_left_arm_sensor />
  </xacro:macro>

  <!-- Actuators -->
  <xacro:macro name="v1_upper_arm_actuators" params="name1 type1 name2 type2 name3 type3 name4 type4">
    <actuator name="${name1}" type="${type1}"/>
    <actuator name="${name2}" type="${type2}"/>
    <actuator name="${name3}" type="${type3}"/>
    <actuator name="${name4}" type="${type4}"/>
  </xacro:macro>

  <xacro:macro name="v1_lower_arm_actuators" params="name1 type1 name2 type2 name3 type3">
    <actuator name="${name1}" type="${type1}"/>
    <actuator name="${name2}" type="${type2}"/>
    <actuator name="${name3}" type="${type3}"/>
  </xacro:macro>

  <xacro:macro name="v1_arm_actuators" params="name1 type1 name2 type2 name3 type3 name4 type4 name5 type5 name6 type6 name7 type7">
    <xacro:v1_upper_arm_actuators name1="${name1}" type1="${type1}" name2="${name2}" type2="${type2}" name3="${name3}" type3="${type3}" name4="${name4}" type4="${type4}"/>
    <xacro:v1_lower_arm_actuators name1="${name5}" type1="${type5}" name2="${name6}" type2="${type6}" name3="${name7}" type3="${type7}" />
  </xacro:macro>
</robot>